version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: manas
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

  springboot-app:
    build: .
    container_name: customer-service-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customerdb
      SPRING_DATASOURCE_USERNAME: manas
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - spring-net

volumes:
  postgres_data:

networks:
  spring-net:
