#base image which has JRE
FROM openjdk:17-jdk-slim

#maintainer of the file
MAINTAINER Manas Vishnoi

#coppy the .jar file to the container
COPY target/customer-service-0.0.1-SNAPSHOT.jar customer-service-0.0.1-SNAPSHOT.jar

#execute the jar placed inside the image (or basically execute command)
ENTRYPOINT [ "java", "-jar", "customer-service-0.0.1-SNAPSHOT.jar" ]