server:
 port: 8081
spring:
  application:
    name: CustomerService
  datasource:
    url: jdbc:postgresql://localhost:5432/CustomerDB-Dev
    username: postgres
    password: Harami@1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      chat:
        options:
          model: gpt-4o-mini
      api-key: something
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
      
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
     